In [ ]:
import numpy as np
import torch
import torch.nn as nn

In [16]:
# Build two simple models
widenet = nn.Sequential(
    nn.Linear(2, 4),  # hidden layer
    nn.Linear(4, 3)     # Output layer
)
# N:B the nn.Linear layer is the transformation matrix layer that gets us from the input to the output. The first argument
#  represents the number of input features, while the second argument represets the number of output features to be fed into the next layer.
# N:B the nn.Linear layer is a linear transformation: y = xA^T + b, where A is the weight matrix and b is the bias vector. The first argument is the number of input features, and the second argument is the number of output features.
deepnet = nn.Sequential(
    nn.Linear(2,2), # hidden layer
    nn.Linear(2,2), # hidden layer
    nn.Linear(2,3)  # Output layer
)

print("Widenet: ", widenet)
print('')
print("Deepnet: ", deepnet)

Widenet:  Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

Deepnet:  Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [7]:
for param in deepnet.named_parameters():
    print(param)
    print('')

('0.weight', Parameter containing:
tensor([[-0.2872,  0.6915],
        [ 0.3539,  0.5389]], requires_grad=True))

('0.bias', Parameter containing:
tensor([-0.1252, -0.0925], requires_grad=True))

('1.weight', Parameter containing:
tensor([[-0.4691,  0.3507],
        [ 0.1407,  0.0367]], requires_grad=True))

('1.bias', Parameter containing:
tensor([-0.4665,  0.4249], requires_grad=True))

('2.weight', Parameter containing:
tensor([[ 0.1803, -0.5038],
        [ 0.6189,  0.2974],
        [-0.5794,  0.7065]], requires_grad=True))

('2.bias', Parameter containing:
tensor([-0.2725,  0.1918,  0.2825], requires_grad=True))



In [ ]:
# Count total number of nodes (By counting the number of biases)
total_nodes_in_widenet = 0
for param in widenet.named_parameters():
    print(param)
    if 'bias' in param[0]: # if the parameter is a bias
        total_nodes_in_widenet += len(param[1]) # add the number of nodes in that layer to the total count

total_nodes_in_deepnet = 0
for param_name, param_vect in deepnet.named_parameters():
    if 'bias' in param_name: # if the parameter is a bias
        total_nodes_in_deepnet += len(param_vect) # add the number of nodes in that layer to the total count

print(f"Total number of nodes in widenet: {total_nodes_in_widenet}")
print(f"Total number of nodes in deepnet: {total_nodes_in_deepnet}")


('0.weight', Parameter containing:
tensor([[-0.2015, -0.1448],
        [-0.0620, -0.1739],
        [-0.4985, -0.0205],
        [-0.3689, -0.0533]], requires_grad=True))
('0.bias', Parameter containing:
tensor([-0.2012,  0.2847, -0.2995, -0.4155], requires_grad=True))
('1.weight', Parameter containing:
tensor([[-0.4069, -0.0006,  0.4860, -0.1378],
        [ 0.4493, -0.0258, -0.0319,  0.0996],
        [ 0.0603, -0.0092, -0.0274,  0.2199]], requires_grad=True))
('1.bias', Parameter containing:
tensor([0.4334, 0.2144, 0.0909], requires_grad=True))
