In [35]:
import numpy as np
import torch
import torch.nn as nn

In [36]:
# Build two simple models
widenet = nn.Sequential(
    nn.Linear(2, 4),  # hidden layer
    nn.Linear(4, 3)     # Output layer
)
# N:B the nn.Linear layer is the transformation matrix layer that gets us from the input to the output. The first argument
#  represents the number of input features, while the second argument represets the number of output features to be fed into the next layer.
# N:B the nn.Linear layer is a linear transformation: y = xA^T + b, where A is the weight matrix and b is the bias vector. The first argument is the number of input features, and the second argument is the number of output features.
deepnet = nn.Sequential(
    nn.Linear(2,2), # hidden layer
    nn.Linear(2,2), # hidden layer
    nn.Linear(2,3)  # Output layer
)

print("Widenet: ", widenet)
print('')
print("Deepnet: ", deepnet)

Widenet:  Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

Deepnet:  Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [37]:
for param in deepnet.named_parameters():
    print(param)
    print('')

('0.weight', Parameter containing:
tensor([[ 0.0146, -0.0544],
        [ 0.2089,  0.5526]], requires_grad=True))

('0.bias', Parameter containing:
tensor([-0.6290,  0.0949], requires_grad=True))

('1.weight', Parameter containing:
tensor([[ 0.4696,  0.2825],
        [ 0.5520, -0.2292]], requires_grad=True))

('1.bias', Parameter containing:
tensor([0.3633, 0.1212], requires_grad=True))

('2.weight', Parameter containing:
tensor([[ 0.6372, -0.0255],
        [-0.6165,  0.6351],
        [-0.6803,  0.3282]], requires_grad=True))

('2.bias', Parameter containing:
tensor([-0.4077, -0.2502, -0.5981], requires_grad=True))



In [38]:
# Count total number of nodes (By counting the number of biases)
total_nodes_in_widenet = 0
for param in widenet.named_parameters():
    print(param)
    if 'bias' in param[0]: # if the parameter is a bias
        total_nodes_in_widenet += len(param[1]) # add the number of nodes in that layer to the total count

total_nodes_in_deepnet = 0
for param_name, param_vect in deepnet.named_parameters():
    if 'bias' in param_name: # if the parameter is a bias
        total_nodes_in_deepnet += len(param_vect) # add the number of nodes in that layer to the total count

print(f"Total number of nodes in widenet: {total_nodes_in_widenet}")
print(f"Total number of nodes in deepnet: {total_nodes_in_deepnet}")


('0.weight', Parameter containing:
tensor([[ 0.4097,  0.2321],
        [ 0.6682,  0.3932],
        [-0.2691, -0.1851],
        [ 0.1051, -0.5412]], requires_grad=True))
('0.bias', Parameter containing:
tensor([0.4579, 0.3215, 0.5441, 0.4910], requires_grad=True))
('1.weight', Parameter containing:
tensor([[-0.3055,  0.4710,  0.0803, -0.1664],
        [-0.3444,  0.4594,  0.3438, -0.1133],
        [-0.4711, -0.2439,  0.2742,  0.1543]], requires_grad=True))
('1.bias', Parameter containing:
tensor([ 0.1394, -0.4191,  0.1655], requires_grad=True))
Total number of nodes in widenet: 7
Total number of nodes in deepnet: 7


In [39]:
# named_parameters returns a tuple of (name, parameter)
# parameter returns a tensor of the parameter, so it actually same as the named_parameters without the name
for param in widenet.parameters():
    print(param)
    print('')

Parameter containing:
tensor([[ 0.4097,  0.2321],
        [ 0.6682,  0.3932],
        [-0.2691, -0.1851],
        [ 0.1051, -0.5412]], requires_grad=True)

Parameter containing:
tensor([0.4579, 0.3215, 0.5441, 0.4910], requires_grad=True)

Parameter containing:
tensor([[-0.3055,  0.4710,  0.0803, -0.1664],
        [-0.3444,  0.4594,  0.3438, -0.1133],
        [-0.4711, -0.2439,  0.2742,  0.1543]], requires_grad=True)

Parameter containing:
tensor([ 0.1394, -0.4191,  0.1655], requires_grad=True)



In [40]:
# Count total number of trainable parameters

number_of_nodes_in_widenet = 0
for param in widenet.parameters():
    if param.requires_grad:
        number_of_nodes_in_widenet += param.numel() # add the number of nodes in that layer to the total count

number_of_nodes_in_deepnet = 0
for param in deepnet.parameters():
    if param.requires_grad:
        number_of_nodes_in_deepnet += param.numel() # add the number of nodes in that layer to the total count

print(f"Total number of nodes in widenet: {number_of_nodes_in_widenet}")
print(f"Total number of nodes in deepnet: {number_of_nodes_in_deepnet}")

Total number of nodes in widenet: 27
Total number of nodes in deepnet: 21


In [41]:
# Using list comprehension
number_of_nodes_in_widenet = sum([param.numel() for param in widenet.parameters() if param.requires_grad])
number_of_nodes_in_deepnet = sum([param.numel() for param in deepnet.parameters() if param.requires_grad])

print(f"Total number of nodes in widenet: {number_of_nodes_in_widenet}")
print(f"Total number of nodes in deepnet: {number_of_nodes_in_deepnet}")

Total number of nodes in widenet: 27
Total number of nodes in deepnet: 21
